require 'rubygems'
require 'bundler'
Bundler.setup
require 'rake'

require 'mg'
MG.new('oa-basic.gemspec')

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |s|
  s.rspec_opts = "--format=#{ENV['RSPEC_FORMAT'] || 'nested'} --colour"
end

task :default => :spec
