name: JRuby
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        jruby: [jruby, jruby-head]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.jruby }}
        bundler-cache: true
      env:
        JRUBY_OPTS: --debug
    - name: Run tests
      env:
        JRUBY_OPTS: --debug
        COVERAGE: true
      run: bundle exec rake
    - name: Coveralls GitHub Action
      if: matrix.os == 'ubuntu'
      uses: coverallsapp/github-action@v2
      with:
        parallel: true
        github-token: ${{ secrets.github_token }}
        path-to-lcov: './coverage/lcov/omniauth.lcov'
        flag-name: ${{ matrix.jruby }}
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true
